### PR TITLE
Add Martha from DEI Working Group and add Carol to emeritus

### PR DESCRIPTION
**Pull request by Zsailer**
Welcome @marthacryan to the SSC (representing the DEI Working Group)! 🎉 

Great to have you here! 

This PR also adds @willingc to our SSC Emeritus section (recently added in the last PR). Carol, massive apologies that we didn't have this page before or add you when we merged it! ❤️

### CODE REVIEW

**Comment by Zsailer** [comment]
I pulled your affiliations from your LinkedIn profiles, so feel free to edit them if they are wrong! 😅

**Comment by Zsailer** [comment]
@jupyter/software-steering-council

**Review by echarles — APPROVED** [review]
LGTM Thx @Zsailer

**Comment by Ruv7** [comment]
For the sake of clarity in the archiving of this issue, can you please update to DEI Standing Committee? The two distinctions have confusing for the community in the past so I want to get them right in our communications. Here is the official list of Jupyter standing committees and working groups: https://jupyter.org/governance/list_of_standing_committees_and_working_groups.html

**Comment by Zsailer** [comment]
Ah yes, thanks for catching this. I'm updated the title.

**Pull request merged**
